language: generic
os: linux

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - ROSWELL_VERSION=20.04.14.105
    - ROSWELL_URL="https://raw.githubusercontent.com/roswell/roswell/v$ROSWELL_VERSION/scripts/install-for-ci.sh"

jobs:
  include:
    - os: linux
      env:
        - LISP=sbcl/2.0.3
        - DEST=ap-linux
    - os: osx
      env:
        - LISP=sbcl/2.0.3
        - DEST=ap-osx
    - os: windows
      language: shell
      env:
        - LISP=sbcl-bin/2.0.0
        - DEST=ap.exe

install:
  - curl -L $ROSWELL_URL | sh
  - |
    if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      choco install make
    fi

script:
  - make binary-ros
  - bin/ap --version
